export async function getPermissions(b_chk) {
  return new Promise((resolve) => {
    resolve([
      // allow access to home section in vertical navbar
      {
        func: "View home section",
        viewAllSectionChk: b_chk,
        name: "viewAllSectionChk",
        id: "home",
        title: "Home section",
        rowSpan: 1,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Bank statement upload
      {
        func: "Upload Bank Statement",
        uploadBankStatementChk: b_chk,
        name: "uploadBankStatementChk",
        id: "bankStatement",
        title: "Bank Statement section",
        rowSpan: 1,
        assignedCompanyId: [],
      },

      //------------------------------------------------------------------------------------------------------------------
      // Report section
      {
        func: "Access to Report",
        accessReport: b_chk,
        name: "accessReport",
        id: "report",
        title: "Report section ",
        rowSpan: 2,
        assignedCompanyId: [],
      },
      {
        func: "View unpaid invoices only",
        viewUnpaidInvoiceOnly: b_chk,
        name: "viewUnpaidInvoiceOnly",
        id: "report",
        title: "",
        rowSpan: 2,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Payment section
      {
        func: "Access to payment section",
        accessPayment: b_chk,
        name: "accessPayment",
        id: "payment",
        title: "Payment section",
        rowSpan: 3,
        assignedCompanyId: [],
      },
      {
        func: "Add full payment/ partial payment",
        addFullPartialPaymentChk: b_chk,
        name: "addFullPartialPaymentChk",
        id: "payment",
        title: "Payment section",
        rowSpan: 3,
        assignedCompanyId: [],
      },
      {
        func: "Delete full payment/ partial payment",
        deleteFullPartialPaymentChk: b_chk,
        name: "deleteFullPartialPaymentChk",
        id: "payment",
        title: "Payment section",
        rowSpan: 3,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Expense section
      {
        func: "Access to expense section",
        accessExpense: b_chk,
        name: "accessExpense",
        id: "expense",
        title: "Expense",
        rowSpan: 3,
        assignedCompanyId: [],
      },
      {
        func: "Add expense",
        addExpense: b_chk,
        name: "addExpense",
        id: "expense",
        title: "Expense",
        rowSpan: 3,
        assignedCompanyId: [],
      },
      {
        func: "Delete expense",
        deleteExpense: b_chk,
        name: "deleteExpense",
        id: "expense",
        title: "Expense",
        rowSpan: 3,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Quotaion
      {
        func: "View quotation",
        viewQuotation: b_chk,
        name: "viewQuotation",
        id: "quotation",
        title: "Quotation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create quotation",
        createQuotation: b_chk,
        name: "createQuotation",
        id: "quotation",
        title: "Quotation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update quotation",
        updateQuotation: b_chk,
        name: "updateQuotation",
        id: "quotation",
        title: "Quotation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete quotation",
        deleteQuotation: b_chk,
        name: "deleteQuotation",
        id: "quotation",
        title: "Quotation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Invoice
      {
        func: "View Invoice",
        viewInvoice: b_chk,
        name: "viewInvoice",
        id: "invoice",
        title: "Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Invoice",
        createInvoice: b_chk,
        name: "createInvoice",
        id: "invoice",
        title: "Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Invoice",
        updateInvoice: b_chk,
        name: "updateInvoice",
        id: "invoice",
        title: "Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Invoice",
        deleteInvoice: b_chk,
        name: "deleteInvoice",
        id: "invoice",
        title: "Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // VAT Invoice
      {
        func: "View VAT Invoice",
        viewVatInvoice: b_chk,
        name: "viewVatInvoice",
        id: "vatInvoice",
        title: "VAT Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create VAT Invoice",
        createVatInvoice: b_chk,
        name: "createVatInvoice",
        id: "vatInvoice",
        title: "VAT Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update VAT Invoice",
        updateVatInvoice: b_chk,
        name: "updateVatInvoice",
        id: "vatInvoice",
        title: "VAT Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete VAT Invoice",
        deleteVatInvoice: b_chk,
        name: "deleteVatInvoice",
        id: "vatInvoice",
        title: "VAT Invoice section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Purchase order
      {
        func: "View Purchase order",
        viewPurchaseOrder: b_chk,
        name: "viewPurchaseOrder",
        id: "purchaseOrder",
        title: "Purchase order section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Purchase order",
        createPurchaseOrder: b_chk,
        name: "createPurchaseOrder",
        id: "purchaseOrder",
        title: "Purchase order section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Purchase order",
        updatePurchaseOrder: b_chk,
        name: "updatePurchaseOrder",
        id: "purchaseOrder",
        title: "Purchase order section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Purchase order",
        deletePurchaseOrder: b_chk,
        name: "deletePurchaseOrder",
        id: "purchaseOrder",
        title: "Purchase order section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Proforma
      {
        func: "View Proforma",
        viewProforma: b_chk,
        name: "viewProforma",
        id: "viewProforma",
        title: "Proforma section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Proforma",
        createProforma: b_chk,
        name: "createProforma",
        id: "viewProforma",
        title: "Proforma section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Proforma",
        updateProforma: b_chk,
        name: "updateProforma",
        id: "viewProforma",
        title: "Proforma section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Proforma",
        deleteProforma: b_chk,
        name: "deleteProforma",
        id: "viewProforma",
        title: "Proforma section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Credit note
      {
        func: "View Credit Note",
        viewCreditNote: b_chk,
        name: "viewCreditNote",
        id: "creditNote",
        title: "Credit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Credit Note",
        createCreditNote: b_chk,
        name: "createCreditNote",
        id: "creditNote",
        title: "Credit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Credit Note",
        updateCreditNote: b_chk,
        name: "updateCreditNote",
        id: "creditNote",
        title: "Credit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Credit Note",
        deleteCreditNote: b_chk,
        name: "deleteCreditNote",
        id: "creditNote",
        title: "Credit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Debit note
      {
        func: "View Debit Note",
        viewDebitNote: b_chk,
        name: "viewDebitNote",
        id: "debitNote",
        title: "Debit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Debit Note",
        createDebitNote: b_chk,
        name: "createDebitNote",
        id: "debitNote",
        title: "Debit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Debit Note",
        updateDebitNote: b_chk,
        name: "updateDebitNote",
        id: "debitNote",
        title: "Debit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Debit Note",
        deleteDebitNote: b_chk,
        name: "deleteDebitNote",
        id: "debitNote",
        title: "Debit note section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Cash Transaction
      {
        func: "View Cash Transation",
        viewCashTransaction: b_chk,
        name: "viewCashTransaction",
        id: "cashTransaction",
        title: "Cash transation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Cash Transation",
        createCashTransaction: b_chk,
        name: "createCashTransaction",
        id: "cashTransaction",
        title: "Cash transation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Cash Transation",
        updateCashTransaction: b_chk,
        name: "updateCashTransaction",
        id: "cashTransaction",
        title: "Cash transation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Cash Transation",
        deleteCashTransaction: b_chk,
        name: "deleteCashTransaction",
        id: "cashTransaction",
        title: "Cash transation section",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Deleted documents
      {
        func: "View Deleted documents",
        viewDeletedDocuments: b_chk,
        name: "viewDeletedDocuments",
        id: "deletedDoc",
        title: "Deleted documents section",
        rowSpan: 2,
        assignedCompanyId: [],
      },
      {
        func: "Undo deletion of a document",
        undoDeletion: b_chk,
        name: "undoDeletion",
        id: "deletedDoc",
        title: "Deleted documents section",
        rowSpan: 2,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Converted proforma
      {
        func: "View converted proforma",
        viewConvertedProforma: b_chk,
        name: "viewConvertedProforma",
        id: "convertedProforma",
        title: "Converted proforma",
        rowSpan: 1,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Calendar
      {
        func: "View calendar",
        viewCalendar: b_chk,
        name: "viewCalendar",
        id: "calendar",
        title: "Calendar",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Add calendar task",
        addCalendarTask: b_chk,
        name: "addCalendarTask",
        id: "calendar",
        title: "Calendar",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update calendar task",
        updateCalendarTask: b_chk,
        name: "updateCalendarTask",
        id: "calendar",
        title: "Calendar",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete calendar task",
        deleteCalendarTask: b_chk,
        name: "deleteCalendarTask",
        id: "calendar",
        title: "Calendar",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Employee
      {
        func: "View Employee",
        viewEmployee: b_chk,
        name: "viewEmployee",
        id: "employee",
        title: "Employee",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Add employee",
        addEmployee: b_chk,
        name: "addEmployee",
        id: "employee",
        title: "Employee",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update employee",
        updateEmployee: b_chk,
        name: "updateEmployee",
        id: "employee",
        title: "Employee",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete employee",
        deleteEmployee: b_chk,
        name: "deleteEmployee",
        id: "employee",
        title: "Employee",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Company
      {
        func: "View Company details",
        viewCompChk: b_chk,
        name: "viewCompChk",
        id: "company",
        title: "Company",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Company",
        createCompChk: b_chk,
        name: "createCompChk",
        id: "company",
        title: "Company",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Company",
        updateCompChk: b_chk,
        name: "updateCompChk",
        id: "company",
        title: "Company",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Company",
        deleteCompChk: b_chk,
        name: "deleteCompChk",
        id: "company",
        title: "Company",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Client
      {
        func: "View Client details",
        viewClientChk: b_chk,
        name: "viewClientChk",
        id: "client",
        title: "Client",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Client",
        createClientChk: b_chk,
        name: "createClientChk",
        id: "client",
        title: "Client",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Client",
        updateClientChk: b_chk,
        name: "updateClientChk",
        id: "client",
        title: "Client",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Client",
        deleteClientChk: b_chk,
        name: "deleteClientChk",
        id: "client",
        title: "Client",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Admins
      {
        func: "View Admin details",
        viewAdminChk: b_chk,
        name: "viewAdminChk",
        id: "admin",
        title: "Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Admin",
        createAdminChk: b_chk,
        name: "createAdminChk",
        id: "admin",
        title: "Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Admin",
        updateAdminChk: b_chk,
        name: "updateAdminChk",
        id: "admin",
        title: "Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Admin",
        deleteAdminChk: b_chk,
        name: "deleteAdminChk",
        id: "admin",
        title: "Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      // Super admin
      {
        func: "View Super Admin details",
        viewSuperAdminChk: b_chk,
        name: "viewSuperAdminChk",
        id: "super-admin",
        title: "Super Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Create Super Admin",
        createSuperAdminChk: b_chk,
        name: "createSuperAdminChk",
        id: "super-admin",
        title: "Super Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Update Super Admin",
        updateSuperAdminChk: b_chk,
        name: "updateSuperAdminChk",
        id: "super-admin",
        title: "Super Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      {
        func: "Delete Super Admin",
        deleteSuperAdminChk: b_chk,
        name: "deleteSuperAdminChk",
        id: "super-admin",
        title: "Super Admin",
        rowSpan: 4,
        assignedCompanyId: [],
      },
      //------------------------------------------------------------------------------------------------------------------
      {
        func: "View client survey",
        viewAllClientSurveyChk: b_chk,
        name: "viewAllClientSurveyChk",
        id: "bugsBeGone",
        title: "Bugs Be Gone Custom Settings",
        rowSpan: 1,
        assignedCompanyId: [],
      },
    ]);
  });
}
