import React from "react";
import CurrencyFormat from "react-currency-format";

function SummaryIncomeReportExcel({ totalObject }) {
  const {
    incomeSummaryTotalTaxableSubtotal,
    incomeSummaryTotalTaxableVat,
    incomeSummaryTotalTaxable,
    incomeSummaryTotalZeroRated,
    incomeSummaryTotalExempt,
    incomeSummaryTotalDisbursement,
    incomeSummaryTotalExemptBodies,

    // table footer
    incomeSummaryTotalSubtotal,
    incomeSummaryTotalVat,
    incomeSummaryTotalOverallAmount,
  } = totalObject;

  return (
    <>
      <thead>
        <tr>
          <th
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            SALES-LOCAL
          </th>
          <th
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            AMOUNT
          </th>
          <th
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            VAT
          </th>
          <th
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            TOTAL
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            TAXABLE
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalTaxableSubtotal || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalTaxableVat || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalTaxable || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
        </tr>
        <tr>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            ZERO-RATED
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalZeroRated || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            -
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalZeroRated || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
        </tr>
        <tr>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            EXEMPT
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalExempt || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            -
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalExempt || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
        </tr>
        <tr>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            DISBURSEMENT
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalDisbursement || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            -
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalDisbursement || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
        </tr>
        <tr>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            TAXABLE SUPPLIES ON EXEMPT BODIES
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalExemptBodies || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            -
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalExemptBodies || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={false}
            data-a-h="center"
          ></td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalSubtotal || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalVat || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
          <td
            data-b-a-s="thin"
            data-b-a-c="00000000"
            data-f-bold={true}
            data-a-h="center"
          >
            <CurrencyFormat
              value={Number(incomeSummaryTotalOverallAmount || 0).toFixed(2)}
              displayType={"text"}
              thousandSeparator={true}
            />
          </td>
        </tr>
      </tfoot>
    </>
  );
}

export default SummaryIncomeReportExcel;
